# version: '3'
# services:
#   node:
#     container_name: vue_seats_generator
#     image: node:20.9.0-alpine3.18
#     volumes:
#       - ./:/app
#     working_dir: /app
#     ports:
#       - 5173:5173
#     command: >
#       sh -c "npm install && npm run dev"
#     restart: always

version: '3'
services:
  node:
    container_name: vue_seats_generator
    image: node:20.9.0-alpine3.18
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 5173:5173
    command: >
      sh -c "npm install --legacy-peer-deps && npm run dev"
    restart: always
